### ISSUE TITLE
[FEATURE]: Add synchronization with Tagger module

### ISSUE THREAD

**Issue by p4535992** [ZotyDev/FoundryVTT-ItemTags#2]
### Discord Username

4535992

### Enhancement Type

Feature

### Request

This module https://github.com/fantasycalendar/FoundryVTT-Tagger/tree/master is widely used at the moment to tag placeable objects on the canvas . To link token <-> actor, or note <-> journal, it might be convenient to keep the tags between these modules synchronized.
Is it possible to add from your side the possibility to set the tags of this module on the document ?

**Comment by ZotyDev** [comment]
Set the tags of Tagger on the ItemTags?

**Comment by p4535992** [comment]
It would have been better to integrate tags on both documents and placeable objects with the same module, but for my use case it would be enough for me to have your tags replicated on the flags of the tagger module and to have a 1:1 relationship between the tags of the actor document and the placeable objects Token connected to it.

**Comment by ZotyDev** [comment]
Hm. Thats doable, I will do a Tagger compatibility asap and release it, after that I will look into a way to tag placeables. Thanks for suggesting this!
PS: I don't want to invade what Tagger does and create a module to make it obsolete, but I don't want to rely on other modules too, interaction between many modules make it harder for me to maintain compatibility, and I plan to index things in a cache later on to make searches nearly instant.

**Comment by ZotyDev** [comment]
Could you share some uses you need it for? It would be nice to have a reference to test this out later.

**Comment by p4535992** [comment]
Sorry ! completely forgot about this.
The use case is that for example when you dredge an actor on the canvas and it becomes a token I would have wanted it to carry tags, but having a lot of stuff already done and integrated with the Tagger module by now, I would have had to rewrite some code.

I'm closing the ticket because we rewrote the code XD.
Ty for you hard work.
